<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoporteTecnico.BL\SoporteTecnico.BL.csproj" />
    <ProjectReference Include="..\SoporteTecnico.DAL\SoporteTecnico.DAL.csproj" />
    <ProjectReference Include="..\SoporteTecnico.EN\SoporteTecnico.EN.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Categorias\" />
    <Folder Include="Views\Tickets\" />
    <Folder Include="Views\Usuarios\" />
  </ItemGroup>

</Project>
